### ISSUE TITLE
Doesn't identify passed pins as pins on raspberry pi with blinka

### ISSUE THREAD

**Issue by Neradoc** [adafruit/Adafruit_CircuitPython_RGBLED#19]
Running on a Pi 3 (python 3.7.3).
```py
import board
import adafruit_rgbled
rgb = adafruit_rgbled.RGBLED(board.D1, board.D2, board.D3)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/adafruit_rgbled.py", line 110, in __init__
    raise TypeError("Must provide a pin, PWMOut, or PWMChannel.")
TypeError: Must provide a pin, PWMOut, or PWMChannel.
```
This line does not identify pins correctly:
https://github.com/adafruit/Adafruit_CircuitPython_RGBLED/blob/cb62700a3760c070dd32752d1a97180cc399aacc/adafruit_rgbled.py#L104-L110

```py
>>> type(board.D1)
<class 'adafruit_blinka.microcontroller.bcm283x.pin.Pin'>
```
Is there a compatible way to actually test if it's a pin ? Just try/except it ?
In Circuitpython a pin is an instance of microcontroller.Pin (for `isinstance`), but not currently in Blinka.
If we are going with strings, there's `board.D1.__class__.__name__ == "Pin"` ?

**Comment by ladyada** [comment]
we dont have pwmout either necessarily, so there might be another test to see if there's a 'value' property? if so, then we can use it as a non-PWM output

**Comment by schnee72** [comment]
I had the same issue, I imported re and changed line 106 to `elif re.match(r"^<class '.*Pin'>$", str(type(self._rgb_led_pins[i]))):`. Not sure if it is ideal or not, but works.

You can see the various use cases for the regex [here](https://regex101.com/r/2IlsV8/1).

**Comment by tekktrik** [comment]
Opening this up for Hacktoberfest!

[The current method for checking if an input is a `Pin`](https://github.com/adafruit/Adafruit_CircuitPython_RGBLED/blob/8887d976a7fb2a9cd8d8dd0f0e4a3ac50d0339bb/adafruit_rgbled.py#L106) is insufficient.  A better method would be to check for a `value` property in the input:

```python
if hasattr(self._rgb_led_pins[i], "value"):
```
